[bot]
# 这里是 KafuBot 自身的配置
event_queue_size=100
nodes = []
node_dirs = ["./nodes"]
adapters = ["sekaibot.adapter.cqhttp"]
adapter_max_retries = 30


[bot.log]
# 这里是 KafuBot 自身日志相关的配置
level = "INFO"
verbose_exception = true

[adapter.cqhttp]
# 这里是 CQHTTP 适配器的配置
adapter_type = "reverse-ws"
host = "127.0.0.1"
port = 8888
url = "/cqhttp/ws"
api_timeout=10

[permission]
superusers = ["2682064633", "3613158872", "2641460187", "group_596488203", "group_1011357049"]

[node.group_chat]
auto_reply_groups=[
    648749016,
    752699901,
    913873554,
    954012874,
    897593721,
    1048490205,
    172844144,
    565525468,
]
interval_seconds=40
activity_limits=[
    [300, 20],
    [3600, 40],
    [18000, 100],
    [604800, 500],
]

[node.private_chat]
merge_window_seconds=5
activity_day=[8,20]
activity_limits=[
    [3600, 30],
    [18000, 80],
    [604800, 400],
]
activity_day_multiplier=0.5
activity_night_multiplier=1.0