[bot]
# 这里是 KafuBot 自身的配置
event_queue_size=100
nodes = []
node_dirs = ["./nodes"]
adapters = ["sekaibot.adapter.cqhttp"]
adapter_max_retries = 30


[bot.log]
# 这里是 KafuBot 自身日志相关的配置
level = "INFO"
verbose_exception = true

[adapter.cqhttp]
# 这里是 CQHTTP 适配器的配置
adapter_type = "reverse-ws"
host = "127.0.0.1"
port = 8888
url = "/cqhttp/ws"
api_timeout=10

[permission]
superusers = ["2682064633", "3613158872", "2641460187", "group_596488203", "group_1011357049"]

[node.private_agent]
merge_window_seconds=5
clear_keywords=["/clear", "/清除"]
average_reply_count=1.3
rate_limit=[0.2, 2]
activity_limits=[
    [3600, 20],
    [18000, 60],
    [604800, 300],
]

[node.group_agent]
unrestricted_groups=[
    596488203,
    1011357049,
    1058218429,
    1087911123,
    834922207,
    895484096,
]
auto_reply_groups=[
    648749016,
    752699901,
    913873554,
    954012874,
    897593721,
    1048490205,
    172844144,
    565525468,
    154243984,
    924342546,
    1074180418,
    983497050,
]
reply_keywords=[
    ["可不", 0.7],
    ["星界", 0.6],
    ["花谱", 0.5],
    ["里命", 0.2],
    ["情绪", 0.1],
]
clear_keywords=["/clear", "/清除"]
talk_value=0.15
average_reply_count=1.2
rate_limit=[0.2, 2]
activity_limits=[
    [3600, 15],
    [18000, 45],
    [604800, 225],
]