DEFAULT_DB_URL = "sqlite:///./.database/expression_learner.db"
DEFAULT_MAX_CONCURRENT_LEARNERS = 3
DEFAULT_EXPRESSION_CHECKED_ONLY = True
DEFAULT_EXPRESSION_SELF_REFLECT = True
DEFAULT_ENABLE_PRECISE_EXPRESSION_SELECTION = False

MIN_CANDIDATE_POOL_SIZE = 10
MAX_HIGH_COUNT_SAMPLE_SIZE = 5
MAX_RANDOM_SAMPLE_SIZE = 5
MAX_PRECISE_SELECTED_EXPRESSIONS = 3
MAX_VISIBLE_CONTEXT_MESSAGES = 10
MAX_LEARNED_EXPRESSIONS_PER_BATCH = 20
SIMILARITY_THRESHOLD = 0.75

EXPRESSION_REVIEW_LOG_PATH = "logs/expression_review/review_logs.json"
AI_REVIEW_EVENT = "ai_review"
MANUAL_RESCUE_EVENT = "manual_rescue"

EXPRESSION_REPLY_SOURCE = "expression_style"
EXPRESSION_SELECTOR_SOURCE = "expression_selector"
EXPRESSION_LEARN_SOURCE = "learn_style"
EXPRESSION_EVALUATION_SOURCE = "expression_evaluation"
EXPRESSION_SUMMARY_SOURCE = "expression_summary"

__all__ = [
    "AI_REVIEW_EVENT",
    "DEFAULT_DB_URL",
    "DEFAULT_ENABLE_PRECISE_EXPRESSION_SELECTION",
    "DEFAULT_EXPRESSION_CHECKED_ONLY",
    "DEFAULT_EXPRESSION_SELF_REFLECT",
    "DEFAULT_MAX_CONCURRENT_LEARNERS",
    "EXPRESSION_EVALUATION_SOURCE",
    "EXPRESSION_LEARN_SOURCE",
    "EXPRESSION_REPLY_SOURCE",
    "EXPRESSION_REVIEW_LOG_PATH",
    "EXPRESSION_SELECTOR_SOURCE",
    "EXPRESSION_SUMMARY_SOURCE",
    "MANUAL_RESCUE_EVENT",
    "MAX_HIGH_COUNT_SAMPLE_SIZE",
    "MAX_LEARNED_EXPRESSIONS_PER_BATCH",
    "MAX_PRECISE_SELECTED_EXPRESSIONS",
    "MAX_RANDOM_SAMPLE_SIZE",
    "MAX_VISIBLE_CONTEXT_MESSAGES",
    "MIN_CANDIDATE_POOL_SIZE",
    "SIMILARITY_THRESHOLD",
]
