import re

FEEDBACK_STATUS_SUCCESS = "success"
FEEDBACK_STATUS_PARTIAL_SUCCESS = "partial_success"
FEEDBACK_STATUS_FAILED = "failed"
FEEDBACK_STATUS_NEUTRAL = "neutral"
ALLOWED_FEEDBACK_STATUSES = {
    FEEDBACK_STATUS_SUCCESS,
    FEEDBACK_STATUS_PARTIAL_SUCCESS,
    FEEDBACK_STATUS_FAILED,
    FEEDBACK_STATUS_NEUTRAL,
}

ACTOR_OTHER_USER = "other_user"
ACTOR_MAIBOT_SELF = "maibot_self"
ACTOR_GROUP_COLLECTIVE = "group_collective"
ACTOR_UNKNOWN = "unknown"
LEARNING_OBSERVED = "observed_behavior"
LEARNING_SELF_REFLECTION = "self_reflection"
ALLOWED_ACTOR_TYPES = {
    ACTOR_OTHER_USER,
    ACTOR_MAIBOT_SELF,
    ACTOR_GROUP_COLLECTIVE,
    ACTOR_UNKNOWN,
}
ALLOWED_LEARNING_TYPES = {LEARNING_OBSERVED, LEARNING_SELF_REFLECTION}

EVIDENCE_HISTORY_LIMIT = 20
FEEDBACK_HISTORY_LIMIT = 30
MIN_BEHAVIOR_SCORE = -6.0
MAX_BEHAVIOR_SCORE = 8.0
NEGATIVE_FEEDBACK_STATUSES = {"failed", "blocked", "abandoned"}
POSITIVE_FEEDBACK_STATUSES = {"success", "succeeded", "completed"}
PARTIAL_POSITIVE_FEEDBACK_STATUSES = {"partial_success"}

MAINTENANCE_COOLDOWN_SECONDS = 60 * 60
DECAY_COOLDOWN_DAYS = 7
UNUSED_DECAY_AFTER_DAYS = 14
UNUSED_DISABLE_AFTER_DAYS = 60
UNRESPONDED_DECAY_AFTER_DAYS = 21
POSITIVE_STALE_DECAY_AFTER_DAYS = 60
MAINTENANCE_SOURCE = "behavior_pattern_maintenance"

MAX_SELECTOR_CANDIDATES = 12
COLD_SINGLETON_BEHAVIOR_FACTOR = 0.45
PROFILE_TAG_MATCH_BONUS_CAP = 0.25
PROFILE_TAG_MATCH_BONUS_FACTOR = 0.35
PROFILE_TAG_MATCH_KINDS = {"attitude", "need"}
MAX_SCENE_CLUSTER_BEHAVIOR_IDS = 48
SCENE_CLUSTER_REUSE_THRESHOLD = 0.72
MIN_TAG_CLUSTER_MERGE_OVERLAP = 2
MAX_TAG_CLUSTER_MEMBERS = 24
DIRECT_DOMAIN_OVERLAP_THRESHOLD = 0.30
DIRECT_DOMAIN_OVERLAP_TOPK = 8
TAG_CLUSTER_SPREAD_TOPK = 8
TAG_CLUSTER_SPREAD_DECAY = 0.5
DIRECT_LOCK_THRESHOLD = 0.60
LOCKED_DIRECT_SPREAD_FACTOR = 0.25

BEHAVIOR_REFERENCE_ID_PATTERN = re.compile(
    r"\bbehavior_id\s*[:\uFF1A]\s*(\d+)\b",
    re.IGNORECASE,
)
BEHAVIOR_SELECTOR_CONTEXT_MESSAGE_LIMIT = 8
BEHAVIOR_SELECTOR_CONTEXT_TEXT_LIMIT = 1800
DEFAULT_MAX_CONCURRENT_LEARNERS = 3
DEFAULT_MAX_FEEDBACK_ATTEMPTS = 3
DEFAULT_DB_URL = "sqlite:///./.database/behavior_learner.db"
TAG_KIND_WEIGHTS = {
    "attitude": 1.1,
    "domain": 1.25,
    "need": 1.25,
}

__all__ = [
    "ACTOR_GROUP_COLLECTIVE",
    "ACTOR_MAIBOT_SELF",
    "ACTOR_OTHER_USER",
    "ACTOR_UNKNOWN",
    "ALLOWED_ACTOR_TYPES",
    "ALLOWED_FEEDBACK_STATUSES",
    "ALLOWED_LEARNING_TYPES",
    "BEHAVIOR_REFERENCE_ID_PATTERN",
    "BEHAVIOR_SELECTOR_CONTEXT_MESSAGE_LIMIT",
    "BEHAVIOR_SELECTOR_CONTEXT_TEXT_LIMIT",
    "COLD_SINGLETON_BEHAVIOR_FACTOR",
    "DECAY_COOLDOWN_DAYS",
    "DEFAULT_DB_URL",
    "DEFAULT_MAX_CONCURRENT_LEARNERS",
    "DEFAULT_MAX_FEEDBACK_ATTEMPTS",
    "DIRECT_DOMAIN_OVERLAP_THRESHOLD",
    "DIRECT_DOMAIN_OVERLAP_TOPK",
    "DIRECT_LOCK_THRESHOLD",
    "EVIDENCE_HISTORY_LIMIT",
    "FEEDBACK_HISTORY_LIMIT",
    "FEEDBACK_STATUS_FAILED",
    "FEEDBACK_STATUS_NEUTRAL",
    "FEEDBACK_STATUS_PARTIAL_SUCCESS",
    "FEEDBACK_STATUS_SUCCESS",
    "LEARNING_OBSERVED",
    "LEARNING_SELF_REFLECTION",
    "LOCKED_DIRECT_SPREAD_FACTOR",
    "MAINTENANCE_COOLDOWN_SECONDS",
    "MAINTENANCE_SOURCE",
    "MAX_BEHAVIOR_SCORE",
    "MAX_SCENE_CLUSTER_BEHAVIOR_IDS",
    "MAX_SELECTOR_CANDIDATES",
    "MAX_TAG_CLUSTER_MEMBERS",
    "MIN_BEHAVIOR_SCORE",
    "MIN_TAG_CLUSTER_MERGE_OVERLAP",
    "NEGATIVE_FEEDBACK_STATUSES",
    "PARTIAL_POSITIVE_FEEDBACK_STATUSES",
    "POSITIVE_FEEDBACK_STATUSES",
    "POSITIVE_STALE_DECAY_AFTER_DAYS",
    "PROFILE_TAG_MATCH_BONUS_CAP",
    "PROFILE_TAG_MATCH_BONUS_FACTOR",
    "PROFILE_TAG_MATCH_KINDS",
    "SCENE_CLUSTER_REUSE_THRESHOLD",
    "TAG_CLUSTER_SPREAD_DECAY",
    "TAG_CLUSTER_SPREAD_TOPK",
    "TAG_KIND_WEIGHTS",
    "UNRESPONDED_DECAY_AFTER_DAYS",
    "UNUSED_DECAY_AFTER_DAYS",
    "UNUSED_DISABLE_AFTER_DAYS",
]
